### ISSUE TITLE
v2.1.0 container image has websocket connection issue

### ISSUE THREAD

**Issue by RicoToothless** [w3f/substrate-telemetry-exporter#37]
I used `web3f/substrate-telemetry-exporter:v2.1.0` container image with config file:

```
subscribe:
  chains:
  - "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
  validators:
  - name: node0
    address: 5D5HUyyooRU3DQKKVXQgvzuMzwdJBks5kwZHvaMgoC6PWgsa
telemetry_host: wss://feed.telemetry.polkadot.io/feed/
```

got the error messages

```
Could not connect to substrate-telemetry on wss://feed.telemetry.polkadot.io/feed/: [object Object]
```

got a similar error with using a different endpoint

```
Could not connect to substrate-telemetry on wss://telemetry.w3f.community/feed: [object Object]
```

I am not sure what the root cause is.

But I changed image base `node:10.16-alpine` to `node:16.13-alpine` in Dockerfile works fine.
